### ISSUE TITLE
do_postgres does work with rubyinstaller version 2.1

### ISSUE THREAD

**Issue by mzibkoff** [datamapper/do#72]
the do_postgres gem does not work under ruby 2.1.x when running under the ruby installer on windows 7. Installation succeeds, but when I try and use it, it fails to load. primarily because the gems\do_postgres-0.10.14-x86-mingw32\lib\do_postgres\2.1\do_postgres.so file seems to be missing. The gem works correctly under ruby 2.0. My guess is because there is a lib/2.0/do_postgres.so available.

I'm using ruby installer, 32 bit, on windows 7.
 
Any help would be appreciated.

**Comment by dbussink** [comment]
This should now be available in the release from today for both 2.1 and 2.2 on Windows.
